### ISSUE TITLE
Site should be rendered on server

### ISSUE THREAD

**Issue by sayedtaqui** [owllux/matreactified#1]
The assignment does not fulfill this requirement for https://lab.maheshtile.in/

> Should be SEO friendly (server-side rendering)

**Comment by owllux** [comment]
Hi @sayedtaqui 
My bad. I missed the SSR part. 

Updated the [SSR version for the theme](https://github.com/owllux/matreactified/tree/master/code-ssr)
Also hosted on a server at http://lab.maheshtile.in:3070/
Please have a look.

Should I apply again for the post or is it ok this comment?
Thanks.

**Comment by sayedtaqui** [comment]
@owllux That is fine, thanks (:

**Comment by owllux** [comment]
@sayedtaqui waiting for an update.
